### ISSUE TITLE
Setup Initial Services Architecture with MSW

### ISSUE THREAD

**Issue by Allandrow** [tantrum-webdev/MTG-deckbuild-react#1]
Link documentation : https://mswjs.io/

- Install MSW
- Create a basic route/handler for testing purposes, not needed to keep it for PR.
- Define / Create basic mock architecture
- Create basic services folder architecture (`mocks` MSW folder inside the `services` folder)

**Comment by Kazay** [comment]
Remove temp files before closing M1
